### ISSUE TITLE
Module fails: No result found

### ISSUE THREAD

**Issue by Xevion** [vaibhavsingh97/random-word#27] opened 2019-08-08 09:37 UTC
**Describe the bug**
Module is completely broken for me. Is it for others?

**To Reproduce**
```python
>>> from random_word import RandomWords
>>> r = RandomWords()
>>> r.get_random_words()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Xevion\AppData\Local\Programs\Python\Python36\lib\site-packages\random_word\random_word.py", line 112, in get_random_words
    "Error occured, No result found. If you think this was a mistake than raise issue at {}".format(self.issue_url))
Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues
>>> r.get_random_word()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Xevion\AppData\Local\Programs\Python\Python36\lib\site-packages\random_word\random_word.py", line 60, in get_random_word
    "Error occured, No result found. If you think this was a mistake than raise issue at {}".format(self.issue_url))
Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues
````

**Expected behavior**
Normal functionality.

**Environment (please complete the following information):**
 - OS: Windows
 - Python 3.6.7

**Additional context**
Had just installed it a second ago. Sorry if it's something dumb, it said to ask here if it's an error, and I think it is...?

**Comment by vaibhavsingh97** [comment] 2019-08-10 01:10
Hi @Xevion, Thanks for reporting. I will look into it and update the module. You may expect an update in a week. Thanks for using my package

**Comment by Scott-St** [comment] 2019-08-10 12:54
Same issue here.

**Comment by AoifeMarieDoherty** [comment] 2019-08-26 20:58
Same here, except one thing to note is that it works (for me) occassionally? For example once every five minutes or so it will work, but only if I do not run it for about 5 minutes once I get the error?

**Comment by Scott-St** [comment] 2019-08-30 16:16
To resolve this request a wordnik API key then change the API key found in config.py of the module.

**Comment by vaibhavsingh97** [comment] 2019-08-30 19:53
Hi,

This is my personal API key i uploaded on pypi if someone needs help then
they can use my package. It got hit, will add an option to use their
personal and key and will add more options to fetch random word. I am quite
late to update the package due to some of my personal commitment, but will
update this package with relevant fix in upcoming days.

**Comment by juan-solorio-program** [comment] 2020-07-13 17:36
Sadly I am experiencing the same issue. Here's the error I get:

Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues

**Comment by vaibhavsingh97** [comment] 2021-02-04 03:05
closing this as a duplicate of https://github.com/vaibhavsingh97/random-word/issues/44

**Closed by vaibhavsingh97** 2021-02-04 03:05 UTC
