### ISSUE TITLE
No result found at word_of_the_day()

### ISSUE THREAD

**Issue by billyeatcookies** [vaibhavsingh97/random-word#43] opened 2020-12-15 14:12 UTC
**Describe the bug**
```
>>> r.word_of_the_day()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\billy\AppData\Roaming\Python\Python38\site-packages\random_word\random_word.py", line 148, in word_of_the_day
    raise Exception(
Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues
```

**To Reproduce**
1. open python console
2. from random_word import RandomWords
3. r = RandomWords()
4. r.word_of_the_day()

**Expected behavior**
shows word of the day

**Screenshots**
![image](https://user-images.githubusercontent.com/70792552/102225723-8e551f00-3f0d-11eb-84c7-fda5e76b566e.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python  3.8

**Additional context**
...

**Comment by ckruger097** [comment] 2020-12-22 16:59
Occurring on Linux as well. get_random_word() raising same Exception.

**Comment by DragonDmoney** [comment] 2021-01-05 20:50
same with me

**Comment by whistletoe** [comment] 2021-01-18 05:36
same issue

**Comment by vaibhavsingh97** [comment] 2021-02-04 02:48
I am working on this issue, closing this as a duplicate of https://github.com/vaibhavsingh97/random-word/issues/44

**Closed by vaibhavsingh97** 2021-02-04 02:48 UTC
