### ISSUE TITLE
Lots of error messages like this

### ISSUE THREAD

**Issue by bitcoinmeetups** [vaibhavsingh97/random-word#31] opened 2020-01-11 07:15 UTC
Nice package. Except these error messages pretty often:

'snortle'
>>> r.get_random_word()
'lophyropoda'
>>> r.get_random_word()
'organolithium'
>>> r.get_random_word()
'foresightful'
>>> r.get_random_word()
'Vesuvius'
>>> r.get_random_word()
'creels'
>>> r.get_random_word()
'knockdowns'
>>> r.get_random_word()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/random_word/random_word.py", lin
e 60, in get_random_word
    "Error occured, No result found. If you think this was a mistake than raise
 issue at {}".format(self.issue_url))
Exception: Error occured, No result found. If you think this was a mistake than
 raise issue at https://github.com/vaibhavsingh97/random-word/issues
>>>

**Comment by stuaxo** [comment] 2020-02-11 11:42
The same thing happened to me, it is the Wordnik API that is returning that message.

TBH if I had known this calls an external API to get it's random word I would have not used this (in fact I cannot use this for work projects).

**Comment by Puhalenthi** [comment] 2020-02-17 22:48
Same Here

**Comment by juan-solorio-program** [comment] 2020-07-13 17:37
I'm experiencing the same issue. Here's the error message I get:

Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues

**Comment by stuaxo** [comment] 2020-07-13 22:16
@juan-solorio-program I would consider finding a random word generator that doesn't use an API to get its random words, apart from this error, it's hugely wasteful to make an HTTP request to do this, and you will hit rate limiting errors like this.

**Comment by vaibhavsingh97** [comment] 2021-02-04 03:04
Thanks for reporting the issue, will update the package, closing it as a duplicate of https://github.com/vaibhavsingh97/random-word/issues/44

**Closed by vaibhavsingh97** 2021-02-04 03:04 UTC
Labels: bug
