### ISSUE TITLE
Cant run the code, am getting an unexpected error message

### ISSUE THREAD

**Issue by SHR3KtheGR3AT** [vaibhavsingh97/random-word#40] opened 2020-08-04 04:45 UTC
**Describe the bug**
when i try to print the random word i am getting the error message 
`Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues`

**To Reproduce**
```
from random_word import RandomWords
w = RandomWords()

word = w.get_random_word()
print(word)
```

**Expected behavior**
it is supposed to print a random word

**Environment (please complete the following information):**
 - OS: Windows
 - Python: 3.8.5

**Screenshots**

![1](https://user-images.githubusercontent.com/68475483/89253799-3f33df00-d63b-11ea-92e7-7f37434a6b7f.png)
![2](https://user-images.githubusercontent.com/68475483/89253805-41963900-d63b-11ea-9553-a7ca4741da5e.png)

**Comment by jackpalaia** [comment] 2020-08-07 22:11
same thing is happening to me

**Comment by HarrazOtame** [comment] 2020-08-10 14:55
Wow... it seems that I'm not alone with this problem... I'm relatively new to programming so there's not much I know about this issue

**Comment by MichaelGitHubHype** [comment] 2020-08-13 17:44
same issue for me

**Comment by tayjaybabee** [comment] 2020-09-12 18:03
I am also having this problem

**Comment by melody-ju** [comment] 2020-09-28 10:17
+1

**Comment by gokart23** [comment] 2020-09-29 09:29
fwiw, for me, this was due to the API rate being exceeded when using the author's key (this package internally queries the Wordnik API). Signing up for a dev account on the Wordnik website and placing my own key at [config.py] worked for me, ymmv.

@vaibhavsingh97 maybe this could be added to the documentation/setup procedure?

**Comment by gboy13** [comment] 2020-10-05 14:19
Same issue. Takes ~ a week to get your own API key. Wish there was a way to use this with a local dictionary.

**Comment by roho2** [comment] 2020-10-15 23:00
Having the same issue. I applied to get a new API key but have to wait a week to find out if it works.

**Comment by vaibhavsingh97** [comment] 2021-02-04 03:01
Thanks for reporting the issue 👍 , I am working on it, a possible duplicate of https://github.com/vaibhavsingh97/random-word/issues/44.

>@vaibhavsingh97 maybe this could be added to the documentation/setup procedure?

I will update the documentation

**Closed by vaibhavsingh97** 2021-02-04 03:01 UTC
